---
init_tasks:
  - name: Add test domain
    type: mysql-client
    script: init_tasks/add_domain.sh
    args: {{ default_domain }}
  
  - name: Reload domains
    type: opensips-cli
    args: -d -x mi domain_reload
    require:
      after:
        task: Add test domain

  - name: Create caller
    type: opensips-cli
    args: -d -x user add {{ caller }}@{{ default_domain }} {{ caller_password }}
    require:
      after:
        task: Reload domains

  - name: Create callee
    type: opensips-cli
    args: -d -x user add {{ callee }}@{{ default_domain }} {{ callee_password }}
    require:
      after:
        task: Reload domains

  - name: Create call forward user
    type: opensips-cli
    args: -d -x user add {{ cf_user }}@{{ default_domain }} {{ cf_pass }}
    require:
      after:
        task: Reload domains
  
  - name: Enable caller
    type: mysql-client
    script: init_tasks/enable_user.sh
    args: {{ caller }} {{ default_domain }}
    require:
      after:
        task: Create caller
        wait: 1
    
  - name: Enable callee
    type: mysql-client
    script: init_tasks/enable_user.sh
    args: {{ callee }} {{ default_domain }}
    require:
      after:
        task: Create callee
        wait: 1

  - name: Enable call forward user
    type: mysql-client
    script: init_tasks/enable_user.sh
    args: {{ cf_user }} {{ default_domain }}
    require:
      after:
        task: Create call forward user
        wait: 1

  - name: Add did for callee
    type: mysql-client
    script: init_tasks/add_did.sh
    args: {{ callee }} {{ default_domain }} {{ callee_did }}

  - name: Add gateway 1
    type: mysql-client
    script: init_tasks/add_gateway.sh
    args:
      - gw-domain-test1
      - sip:{{ gateway1_ip }}:{{ gateway1_port }}
      - 'Gateway Test 1'

  - name: Add gateway 2
    type: mysql-client
    script: init_tasks/add_gateway.sh
    args:
      - gw-domain-test2
      - sip:{{ gateway2_ip }}:{{ gateway2_port }}
      - 'Gateway Test 2'

  - name: Add rule
    type: mysql-client
    script: init_tasks/add_rule.sh
    args:
      - {{ outgoing_did }}
      - gw-domain-test1,gw-domain-test2
      - 'Specific test DID routing'
    require:
      - after:
          task: Add gateway 1
      - after:
          task: Add gateway 2
  
  - name: MI reload dr
    type: opensips-cli
    args: -d -x mi dr_reload
    require:
      - after: Add rule


cleanup_tasks:
  - name: Delete rule
    type: mysql-client
    script: cleanup_tasks/delete_rule.sh
    args: {{ outgoing_did }}

  - name: Delete gateway 1
    type: mysql-client
    script: cleanup_tasks/delete_gateway.sh
    args: 'sip:{{ gateway1_ip }}:{{ gateway1_port }}'

  - name: Delete gateway 2
    type: mysql-client
    script: cleanup_tasks/delete_gateway.sh
    args: 'sip:{{ gateway2_ip }}:{{ gateway2_port }}'

  - name: MI reload gateway after delete
    type: opensips-cli
    args: -d -x mi dr_reload
    require:
      - after: Delete rule
      - after: Delete gateway 1
      - after: Delete gateway 2

  - name: Delete callee did
    type: mysql-client
    script: cleanup_tasks/delete_did.sh
    args: {{ callee_did }}

  - name: Delete caller
    type: opensips-cli
    args: -d -x user delete {{ caller }}@{{ default_domain }}

  - name: Delete callee
    type: opensips-cli
    args: -d -x user delete {{ callee }}@{{ default_domain }}

  - name: Delete call forward user
    type: opensips-cli
    args: -d -x user delete {{ cf_user }}@{{ default_domain }}

  - name: Delete caller AOR
    type: opensips-cli
    args: -d -x mi ul_rm location {{ caller }}@{{ default_domain }}

  - name: Delete callee AOR
    type: opensips-cli
    args: -d -x mi ul_rm location {{ callee }}@{{ default_domain }}
  
  - name: Delete call forward user AOR
    type: opensips-cli
    args: -d -x mi ul_rm location {{ cf_user }}@{{ default_domain }}

  - name: Delete test domain
    type: mysql-client
    script: cleanup_tasks/remove_domain.sh
    args: {{ default_domain }}
    require:
      - after: Delete caller
      - after: Delete callee
  
  - name: Reload domains
    type: opensips-cli
    args: -d -x mi domain_reload
    require:
      after: Delete test domain


defaults:
  opensips-cli:
    mi_ip: {{ opensips_ip }}
    options:
      database_user_url: mysql://{{ mysql_user }}:{{ mysql_password }}@{{ opensips_ip }}/{{ database }}
  uac-sipp:
    proxy: {{ opensips_ip }}:{{ opensips_port }}
    keys:
      domain: {{ default_domain }}
      caller: {{ caller }}
      callee: {{ callee }}
  mysql-client:
    host: {{ opensips_ip }}
    port: {{ mysql_port }}
    user: {{ mysql_user }}
    password: {{ mysql_password }}
    database: {{ database }}
