---
name: Run SIPSsert tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * Mon'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Environment
      run: |
        HOST_IP=$(hostname -I | cut -d ' ' -f 1)
        sed "s/^HOST_IP=.*/HOST_IP=$HOST_IP/g" -i .env
        while read line; do
          [ "$line" = "" ] && continue;
          echo "$line" >> $GITHUB_ENV
        done < .env
      shell: bash

    - name: Setup Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.2

    - name: Prepare SIPssert
      uses: OpenSIPS/SIPssert/.github/actions/Prepare_SIPssert@main
      with:
        sipssert-repo: OpenSIPS/SIPSsert

    - name: Debug Test Setup
      run: |
        echo "Listing directory contents:"
        ls -la
        ls -la sipssert-tests/

    - name: Run Test
      uses: OpenSIPS/SIPssert/.github/actions/Run_Tests@main
      with:
        directory: sipssert-tests
        tests: .

